# Generated by Django 3.2 on 2023-05-12 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2023, 5, 19, 15, 39, 40, 851140, tzinfo=utc))),
            ],
            options={
                'managed': False,
            },
            bases=('authtoken.token',),
        ),
    ]
