# Generated by Django 3.2 on 2023-05-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customtokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtoken',
            options={},
        ),
    ]
