# Generated by Django 3.2 on 2023-05-27 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customtokens', '0002_alter_customtoken_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 9, 28, 53, 994829, tzinfo=utc)),
        ),
    ]
