# Generated by Django 3.2 on 2023-05-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customtokens', '0003_alter_customtoken_expire_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtoken',
            options={'managed': False},
        ),
    ]
