# Generated by Django 3.2 on 2023-05-13 07:12

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_of_posts', models.IntegerField()),
                ('fb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fb_name', models.CharField(blank=True, max_length=200, null=True)),
                ('fb_email', models.CharField(blank=True, max_length=200, null=True)),
                ('fb_profile_pic_link', models.CharField(blank=True, max_length=200, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fb', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
