# Generated by Django 3.2 on 2023-05-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fbdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FBDetails',
            new_name='UserFbDetails',
        ),
    ]
