# Generated by Django 3.2 on 2023-05-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_fbdetails_userfbdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfbdetails',
            name='no_of_posts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
