# Generated by Django 3.2 on 2023-05-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userfbdetails_no_of_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
