# Generated by Django 3.2 on 2023-05-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_influencer_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
