# Generated by Django 3.2 on 2023-05-13 13:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230513_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='https://hoti.s3.ap-south-1.amazonaws.com/media/default_images/userstatic.png', upload_to=accounts.models.generate_profile_image_path),
        ),
    ]
