# Generated by Django 4.2 on 2023-05-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfbdetails',
            name='data',
            field=models.JSONField(),
        ),
    ]
