# Generated by Django 3.2 on 2023-05-24 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userfbdetails_data'),
    ]

    operations = [
    #     migrations.CreateModel(
    #         name='UserInstaDetails',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('ig_id', models.CharField(max_length=255)),
    #             ('username', models.CharField(max_length=255)),
    #             ('followers_count', models.IntegerField(blank=True, null=True)),
    #             ('media_count', models.IntegerField(blank=True, null=True)),
    #             ('average_likes', models.FloatField(blank=True, null=True)),
    #             ('average_comments', models.FloatField(blank=True, null=True)),
    #             ('average_video_views', models.FloatField(blank=True, null=True)),
    #             ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insta_details', to=settings.AUTH_USER_MODEL)),
    #         ],
    #     ),
    ]
