# Generated by Django 3.2 on 2023-05-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userinstadetails'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='userwishlistitems',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='userwishlistitems',
        #     name='updated_at',
        # ),
    ]
