# Generated by Django 3.2 on 2023-05-24 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20230524_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwishlistitems',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userwishlistitems',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
