# Generated by Django 3.2 on 2023-05-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_emailotp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
