# Generated by Django 3.2 on 2023-05-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('accounts', '0017_emailotp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='master.ContentCategory'),
        ),
    ]
