# Generated by Django 3.2 on 2023-05-27 09:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_influencer_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.CharField(blank=True, choices=[('UnVerified', 'UnVerified'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default_images/userstatic.png', upload_to=accounts.models.generate_profile_image_path),
        ),
    ]
