# Generated by Django 4.0 on 2023-06-05 06:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_is_verified_user_verified_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default_images/userstatic.png', null=True, upload_to=accounts.models.generate_profile_image_path),
        ),
    ]
