# Generated by Django 4.0 on 2023-06-05 06:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default_images/userstatic.png', upload_to=accounts.models.generate_profile_image_path),
        ),
    ]
