# Generated by Django 3.2 on 2023-06-12 11:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default_images/userstatic.png', upload_to=accounts.models.generate_profile_image_path),
        ),
    ]
