# Generated by Django 3.2 on 2023-06-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
